cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'


urlpatterns = [
    path('', views.cart_detail, name='cart_detail'),
    path('add/<int:product_id>/', views.cart_add, name='cart_add'),
    path('remove/<int:product_id>/', views.cart_remove, name='cart_remove'),
]

shop/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('store.urls')),
    path('cart/', include('cart.urls')),
]

store/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views

# from store.views import HomePageView, ProductDetailView, CategoryView, CategoryDetailView, register
from store import views

app_name = 'store'


urlpatterns = [
    path('', views.HomePageView.as_view(), name='home'),
    path('product/<int:pk>/', views.ProductDetailView.as_view(), name='product_details'),
    path('categories/', views.CategoryView.as_view(), name='category'),
    path('category/<int:pk>/', views.CategoryDetailView.as_view(), name='category_details'),
    path('register/', views.register, name='register'),
    path('login/', auth_views.LoginView.as_view(), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), {'next_page': '/'}, name='logout'),
]

cart/models.py
from django.db import models

# Create your models here.

store/models.py
from django.db import models
from django.urls import reverse


class Categories(models.Model):
    category_name = models.CharField(max_length=50)

    class Meta:
        verbose_name_plural = 'categories'

    # def get_absolute_url(self):
    #     return reverse('store:store_list')

    def __str__(self):
        return self.category_name

    @property
    def get_products(self):
        return Product.objects.filter(category=self.name)


class Product(models.Model):
    name = models.CharField(max_length=50)
    description = models.TextField()
    price = models.FloatField(default=True)
    category = models.ForeignKey(Categories, on_delete=models.CASCADE)
    image_url = models.CharField(max_length=2083, default=True)
    size = models.PositiveSmallIntegerField()
    colour = models.CharField(max_length=50)

    def __str__(self):
        return f'{self.name}'

cart/forms.py
from django import forms


PRODUCT_QUANTITY_CHOICES = [(qty, str(qty)) for qty in range(1, 21)]


class AddProductForm(forms.Form):
    quantity = forms.TypedChoiceField(choices=PRODUCT_QUANTITY_CHOICES, coerce=int)
    override = forms.BooleanField(widget=forms.HiddenInput)

store/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User


class RegisterForm(UserCreationForm):
    first_name = forms.CharField(max_length=50)
    last_name = forms.CharField(max_length=50)
    email = forms.EmailField(help_text='Please enter a valid email address.')

    class Meta:
        model = User
        fields = ('username', 'first_name', 'last_name', 'email', 'password1', 'password2',)

cart/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.decorators.http import require_POST
from store.models import Product
from cart.cart import ShoppingCart
from cart.forms import AddProductForm


@require_POST
def cart_add(request, product_id):
    cart = ShoppingCart(request)
    product = get_object_or_404(Product, id=product_id)
    form = AddProductForm(request.POST)
    if form.is_valid():
        cd = form.cleaned_data
        cart.add(product=product, quantity=cd['quantity'], override_quantity=cd['override'])
    return redirect('cart:cart_detail')


def cart_remove(request, product_id):
    cart = ShoppingCart(request)
    product = get_object_or_404(Product, id=product_id)
    cart.remove(product)
    return redirect('cart:cart_detail')


def cart_detail(request):
    cart = ShoppingCart(request)
    return render(request, 'cart/cart_detail.html', {'cart': cart})

store/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import login, authenticate
from django.contrib.auth.forms import UserCreationForm
from django.views.generic import ListView, DetailView

from store.models import Product, Categories
from store.forms import RegisterForm
from cart.forms import AddProductForm


class HomePageView(ListView):
    model = Product
    template_name = 'store/home.html'
    context_object_name = 'store_list'


class ProductDetailView(DetailView):
    model = Product
    template_name = 'store/product_details.html'
    cart_form = AddProductForm()


class CategoryView(ListView):
    model = Categories
    template_name = 'store/category.html'
    context_object_name = 'category_list'


class CategoryDetailView(DetailView):
    model = Categories
    template_name = 'store/category_detail.html'
    context_object_name = 'category_details'


def register(request):
    if request.method == 'POST':
        form = RegisterForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            raw_password = form.cleaned_data.get('password1')
            user = authenticate(username=username, password=raw_password)
            login(request, user)
            return redirect('store_list:home')
    else:
        form = RegisterForm()
    return render(request, 'store/register.html', {'form': form})

cart/templates/cart/cart_detail.html
{% extends 'base.html' %}

{% block title %}Shopping Cart{% endblock %}

{% block content %}
<h1>Your shopping cart</h1>
<table class="cart">
    <thead>
    <tr>
        <th>Image</th>
        <th>Product</th>
        <th>Quantity</th>
        <th>Remove</th>
        <th>Unit price</th>
        <th>Price</th>
    </tr>
    </thead>
    <tbody>
    {% for item in cart %}
    {% with product=item.product %}
    <tr>
        <td>
            <a href="{{ product.get_absolute_url }}">
                <img src="{% if product.image %}{{ product.image.url
}}
                {% else %}

                {% endif %}">
            </a>
        </td>
        <td>{{ product.name }}</td>
        <td>{{ item.quantity }}</td>
        <td>
            <form action="{% url 'cart:cart_remove' product.id %}"
                  method="post">
                <input type="submit" value="Remove">
                {% csrf_token %}
            </form>
        </td>
        <td class="num">${{ item.price }}</td>
        <td class="num">${{ item.total_price }}</td>
    </tr>
    {% endwith %}
    {% endfor %}
    <tr class="total">
        <td>Total</td>
        <td colspan="4"></td>
        <td class="num">${{ cart.get_total_price }}</td>
    </tr>
    </tbody>
</table>
<p class="text-right">
    <a href="{% url 'store:home' %}" class="button
 light">Continue shopping</a>
    <a href="#" class="button">Checkout</a>
</p>

{% endblock %}

store/templates/store/category.html
{% extends 'base.html' %}

{% block content %}

<!-- Page Content -->
<div class="container">

  <div class="row">
    <!-- /.col-lg-3 -->

    <div class="col-lg-9">

      <div id="carouselExampleIndicators" class="carousel slide my-4" data-ride="carousel">
        <ol class="carousel-indicators">
          <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
          <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
          <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
        </ol>
        <div class="carousel-inner" role="listbox">
          <div class="carousel-item active">
            <img class="d-block img-fluid" src="https://res.cloudinary.com/praiseey/image/upload/v1598060405/blouse_cnwtqr.jpg" alt="First slide">
          </div>
          <div class="carousel-item">
            <img class="d-block img-fluid" src="https://res.cloudinary.com/praiseey/image/upload/v1598060061/set2_mwlrpe.jpg" alt="Second slide">
          </div>
          <div class="carousel-item">
            <img class="d-block img-fluid" src="https://res.cloudinary.com/praiseey/image/upload/v1598060060/set_u5efbo.jpg" alt="Third slide">
          </div>
        </div>
        <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
          <span class="carousel-control-prev-icon" aria-hidden="true"></span>
          <span class="sr-only">Previous</span>
        </a>
        <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
          <span class="carousel-control-next-icon" aria-hidden="true"></span>
          <span class="sr-only">Next</span>
        </a>
      </div>

      <div class="row">
        {% for item in category_list %}
        <div class="col-lg-4 col-md-6 mb-4">

          <div class="card h-100">
            <a href="#"><img class="card-img-top" src="http://placehold.it/700x400" alt=""></a>
            <div class="card-body">
              <h4 class="card-title">
                <a href="{% url 'store:category_details' item.pk %}">{{item.category_name}}</a>
              </h4>
            </div>

          </div>

        </div>
        {% endfor %}

      </div>
      <!-- /.row -->

    </div>
    <!-- /.col-lg-9 -->

  </div>
  <!-- /.row -->

</div>
<!-- /.container -->

{% endblock %}

store/templates/store/category_detail.html
{% extends 'base.html' %}

{% block content %}

<!-- Page Content -->
<div class="container">

  <div class="row">

    <!-- Categories Change this block to link back to categories page-->
    <div class="col-lg-3">

      <h1 class="my-4">Anni's</h1>
      <div class="list-group">
        <a href="{% url 'store:category' %}" class="list-group-item">Categories</a>
      </div>

    </div>
    <!-- /.col-lg-3 -->

    <div class="col-lg-9">

      <div id="carouselExampleIndicators" class="carousel slide my-4" data-ride="carousel">
        <ol class="carousel-indicators">
          <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
          <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
          <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
        </ol>
        <div class="carousel-inner" role="listbox">
          <div class="carousel-item active">
            <img class="d-block img-fluid" src="http://placehold.it/900x350" alt="First slide">
          </div>
          <div class="carousel-item">
            <img class="d-block img-fluid" src="http://placehold.it/900x350" alt="Second slide">
          </div>
          <div class="carousel-item">
            <img class="d-block img-fluid" src="http://placehold.it/900x350" alt="Third slide">
          </div>
        </div>
        <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
          <span class="carousel-control-prev-icon" aria-hidden="true"></span>
          <span class="sr-only">Previous</span>
        </a>
        <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
          <span class="carousel-control-next-icon" aria-hidden="true"></span>
          <span class="sr-only">Next</span>
        </a>
      </div>

      <div class="row">
        {% for item in category_detail %}
        <div class="col-lg-4 col-md-6 mb-4">
          <h1>{{item}}</h1>

          {% for product in item.get_products %}
            {{ product }}
          {% endfor %}
         {% endfor %}
          <div class="card h-100">
            <a href="#"><img class="card-img-top" src="http://placehold.it/700x400" alt=""></a>
            <div class="card-body">
              <h4 class="card-title">
                <a href="#">{{item.name}}</a>
              </h4>
              <h5>{{item.price}}</h5>
              <p class="card-text">{{item.description}}</p>
            </div>

          </div>

        </div>


      </div>
      <!-- /.row -->

    </div>
    <!-- /.col-lg-9 -->

  </div>
  <!-- /.row -->

</div>
<!-- /.container -->

{% endblock %}

store/templates/store/home.html
{% extends 'base.html' %}

{% block content %}

<!-- Page Content -->
<div class="container">

  <div class="row">

    <!-- Categories -->
    <div class="col-lg-3">

      <h1 class="my-4">Anni's</h1>
      <div class="list-group">
        <a href="{% url 'store:category' %}" class="list-group-item">Categories</a>
      </div>

    </div>
    <!-- /.col-lg-3 -->

    <div class="col-lg-9">

      <div id="carouselExampleIndicators" class="carousel slide my-4" data-ride="carousel">
        <ol class="carousel-indicators">
          <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
          <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
          <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
        </ol>
        <div class="carousel-inner" role="listbox">
          <div class="carousel-item active">
            <img class="d-block img-fluid" src="https://res.cloudinary.com/praiseey/image/upload/v1598060405/blouse_cnwtqr.jpg" alt="First slide">
          </div>
          <div class="carousel-item">
            <img class="d-block img-fluid" src="https://res.cloudinary.com/praiseey/image/upload/v1598060061/set2_mwlrpe.jpg" alt="Second slide">
          </div>
          <div class="carousel-item">
            <img class="d-block img-fluid" src="https://res.cloudinary.com/praiseey/image/upload/v1598060060/set_u5efbo.jpg" alt="Third slide">
          </div>
        </div>
        <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
          <span class="carousel-control-prev-icon" aria-hidden="true"></span>
          <span class="sr-only">Previous</span>
        </a>
        <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
          <span class="carousel-control-next-icon" aria-hidden="true"></span>
          <span class="sr-only">Next</span>
        </a>
      </div>

      <div class="row">
        {% for item in store_list %}
        <div class="col-lg-4 col-md-6 mb-4">

          <div class="card h-100">
            <a href="#"><img class="card-img-top" src="{{ item.image_url }}" alt=""></a>
            <div class="card-body">
              <h4 class="card-title">
                <a href="{% url 'store:product_details' item.pk %}">{{item.name}}</a>
              </h4>
              <h5>N{{item.price}}</h5>
              <p class="card-text">{{item.description}}</p>
            </div>

          </div>

        </div>
        {% endfor %}

      </div>
      <!-- /.row -->

    </div>
    <!-- /.col-lg-9 -->

  </div>
  <!-- /.row -->

</div>
<!-- /.container -->

{% endblock %}

store/templates/store/login.html
<!--{% extends 'base.html' %}-->

<!--{% block title %}Login{% endblock %}-->
<!---->
<!--{% block content %}-->
<!--	<h2>Sign In</h2>-->
<!--	<form method="post">-->
<!--		{% csrf_token %}-->
<!--		{{form.as_p}}-->
<!--		<button type="submit">Sign In</button>-->
<!--	</form>-->
<!--	-->
<!--{% endblock %}-->

store/templates/store/product_details.html
{% extends 'base.html' %}

{% block content %}

<!-- Page Content -->
<div class="container">

<div class="row">

  <div class="col-lg-3">
    <h1 class="my-4">Anni's</h1>
    <div class="list-group">
      <a href="{% url 'store:category' %}" class="list-group-item active">Categories</a>
    </div>
  </div>
  <!-- /.col-lg-3 -->

  <div class="col-lg-9">

    <div class="card mt-4">
      <img class="card-img-top img-fluid" src="{{ object.image_url }}" alt="">
      <div class="card-body">
        <h3 class="card-title">{{object.name}}</h3>
        <h4>N{{object.price}}</h4>
        <p class="card-text">{{object.description}}</p>
        <form action="{% url 'cart:cart_add' product.id %}" method="post">
          {{ cart_form }}
          {% csrf_token %}
          <input type="submit" value="Add to Cart">
        </form>
      </div>
    </div>
    <!-- /.card -->


  </div>
  <!-- /.col-lg-9 -->

</div>

</div>
<!-- /.container -->


{% endblock %}

store/templates/store/register.html
{% extends 'base.html' %}

{% block content %}
    <h2>Create your Account</h2>
	<form method="post">
		{% csrf_token %}
		{{ form.as_p }}
		<button type="submit">Register</button>
	</form>

{% endblock %}

templates/base.html
{% load static %}


<!DOCTYPE html>
<html lang="en">

<head>

  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="description" content="">
  <meta name="author" content="">

  <title>Anni's Shop</title>

  <!--Bootstrap core Javascript -->
  <script src="{% static 'store/vendor/jquery/jquery.min.js' %}"></script>
  <script src="{% static 'store/vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>

  <!-- Bootstrap core CSS -->
  <link href="{% static 'store/vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">

  <!-- Custom styles for this template -->
  <link href="{% static 'store/css/shop-homepage.css' %}" rel="stylesheet">

</head>

<body>

  <!-- Navigation -->
  <nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">
    <div class="container">
      <a class="navbar-brand" href="{% url 'store:home' %}">Anni's</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarResponsive">
        <ul class="navbar-nav ml-auto">
          <li class="nav-item active">
            <a class="nav-link" href="{% url 'store:home' %}">Home
              <span class="sr-only">(current)</span>
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'store:register' %}">Sign Up</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'store:login' %}">Sign In</a>
          </li>

        </ul>
      </div>
    </div>
  </nav>

  {% if user.is_authenticated %}
    <p>Hello {{ user.username }}!</p>
    <p><a href="{% url 'store:logout' %}">Log Out</a></p>
  {% else %}
    <p>You are not logged in.</p>
    <a href="{% url 'store:login' %}">Log In</a>
  {% endif %}

  <!-- Page Content -->
  {% block content %}

  {% endblock %}

  <!-- Footer -->
  <footer class="py-5 bg-dark">
    <div class="container">
      <p class="m-0 text-center text-white">Copyright &copy; Anni's 2020</p>
    </div>
    <!-- /.container -->
  </footer>

  <!-- Bootstrap core JavaScript -->
  <script src="vendor/jquery/jquery.min.js"></script>
  <script src="vendor/bootstrap/js/bootstrap.bundle.min.js"></script>


</body>

</html>